swagger: "2.0"
info:
  title: REST gw
  description: project assembler rest gateway
  version: 1.0.0

host: host
basePath: /
schemes:
  - https
  - http

paths:
  /projects:
    get:
      operationId: getProjects
      summary: returns all projects
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: <PROJECTS_ADDRESS_HERE>
    post:
      operationId: createProject
      summary: create a new project
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: <PROJECTS_ADDRESS_HERE>

  /projects/{id}/join:
    put:
      operationId: joinProject
      summary: join a project
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: id of project to join 
          required: true
          type: string
      responses:
        201:
          description: OK
      x-google-backend:
        address: <PROJECTS_ADDRESS_HERE>
        path_translation: APPEND_PATH_TO_ADDRESS

  /user:
    get:
      operationId: getUser
      summary: get a user by name, email, or fields of expertise
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: <USERS_ADDRESS_HERE>
  
  /user:
    post:
      operationId: createUser
      summary: create a new user
      produces:
        - application/json
      responses:
        201:
          description: OK
      x-google-backend:
        address: <USERS_ADDRESS_HERE>
  
  /user:
    put:
      operationId: updateUser
      summary: update user info
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: <USERS_ADDRESS_HERE>
